// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EcuData : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EcuData {
        __init(_i, _bb)
        return this
    }
    val version : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val versionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun versionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val ecuName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val ecuNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun ecuNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val revision : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val revisionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun revisionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    fun metadata(j: Int) : dataformat.KeyValue? = metadata(dataformat.KeyValue(), j)
    fun metadata(obj: dataformat.KeyValue, j: Int) : dataformat.KeyValue? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val metadataLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    fun featureFlags(j: Int) : Byte {
        val o = __offset(12)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1)
        } else {
            0
        }
    }
    val featureFlagsLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    val featureFlagsAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun featureFlagsInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    fun functClasses(j: Int) : dataformat.FunctClass? = functClasses(dataformat.FunctClass(), j)
    fun functClasses(obj: dataformat.FunctClass, j: Int) : dataformat.FunctClass? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val functClassesLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    fun units(j: Int) : dataformat.Unit? = units(dataformat.Unit(), j)
    fun units(obj: dataformat.Unit, j: Int) : dataformat.Unit? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val unitsLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    fun dops(j: Int) : dataformat.DOP? = dops(dataformat.DOP(), j)
    fun dops(obj: dataformat.DOP, j: Int) : dataformat.DOP? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val dopsLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    fun tables(j: Int) : dataformat.TableDop? = tables(dataformat.TableDop(), j)
    fun tables(obj: dataformat.TableDop, j: Int) : dataformat.TableDop? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val tablesLength : Int
        get() {
            val o = __offset(20); return if (o != 0) __vector_len(o) else 0
        }
    fun tableRows(j: Int) : dataformat.TableRow? = tableRows(dataformat.TableRow(), j)
    fun tableRows(obj: dataformat.TableRow, j: Int) : dataformat.TableRow? {
        val o = __offset(22)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val tableRowsLength : Int
        get() {
            val o = __offset(22); return if (o != 0) __vector_len(o) else 0
        }
    fun params(j: Int) : dataformat.Param? = params(dataformat.Param(), j)
    fun params(obj: dataformat.Param, j: Int) : dataformat.Param? {
        val o = __offset(24)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val paramsLength : Int
        get() {
            val o = __offset(24); return if (o != 0) __vector_len(o) else 0
        }
    fun requests(j: Int) : dataformat.Request? = requests(dataformat.Request(), j)
    fun requests(obj: dataformat.Request, j: Int) : dataformat.Request? {
        val o = __offset(26)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val requestsLength : Int
        get() {
            val o = __offset(26); return if (o != 0) __vector_len(o) else 0
        }
    fun responses(j: Int) : dataformat.Response? = responses(dataformat.Response(), j)
    fun responses(obj: dataformat.Response, j: Int) : dataformat.Response? {
        val o = __offset(28)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val responsesLength : Int
        get() {
            val o = __offset(28); return if (o != 0) __vector_len(o) else 0
        }
    fun diagCodedTypes(j: Int) : dataformat.DiagCodedType? = diagCodedTypes(dataformat.DiagCodedType(), j)
    fun diagCodedTypes(obj: dataformat.DiagCodedType, j: Int) : dataformat.DiagCodedType? {
        val o = __offset(30)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val diagCodedTypesLength : Int
        get() {
            val o = __offset(30); return if (o != 0) __vector_len(o) else 0
        }
    fun sds(j: Int) : dataformat.SD? = sds(dataformat.SD(), j)
    fun sds(obj: dataformat.SD, j: Int) : dataformat.SD? {
        val o = __offset(32)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val sdsLength : Int
        get() {
            val o = __offset(32); return if (o != 0) __vector_len(o) else 0
        }
    fun sdgs(j: Int) : dataformat.SDG? = sdgs(dataformat.SDG(), j)
    fun sdgs(obj: dataformat.SDG, j: Int) : dataformat.SDG? {
        val o = __offset(34)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val sdgsLength : Int
        get() {
            val o = __offset(34); return if (o != 0) __vector_len(o) else 0
        }
    fun sdgss(j: Int) : dataformat.SDGS? = sdgss(dataformat.SDGS(), j)
    fun sdgss(obj: dataformat.SDGS, j: Int) : dataformat.SDGS? {
        val o = __offset(36)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val sdgssLength : Int
        get() {
            val o = __offset(36); return if (o != 0) __vector_len(o) else 0
        }
    fun diagServices(j: Int) : dataformat.DiagService? = diagServices(dataformat.DiagService(), j)
    fun diagServices(obj: dataformat.DiagService, j: Int) : dataformat.DiagService? {
        val o = __offset(38)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val diagServicesLength : Int
        get() {
            val o = __offset(38); return if (o != 0) __vector_len(o) else 0
        }
    fun singleEcuJobs(j: Int) : dataformat.SingleEcuJob? = singleEcuJobs(dataformat.SingleEcuJob(), j)
    fun singleEcuJobs(obj: dataformat.SingleEcuJob, j: Int) : dataformat.SingleEcuJob? {
        val o = __offset(40)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val singleEcuJobsLength : Int
        get() {
            val o = __offset(40); return if (o != 0) __vector_len(o) else 0
        }
    fun variants(j: Int) : dataformat.Variant? = variants(dataformat.Variant(), j)
    fun variants(obj: dataformat.Variant, j: Int) : dataformat.Variant? {
        val o = __offset(42)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val variantsLength : Int
        get() {
            val o = __offset(42); return if (o != 0) __vector_len(o) else 0
        }
    fun functionalGroups(j: Int) : dataformat.FunctionalGroup? = functionalGroups(dataformat.FunctionalGroup(), j)
    fun functionalGroups(obj: dataformat.FunctionalGroup, j: Int) : dataformat.FunctionalGroup? {
        val o = __offset(44)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val functionalGroupsLength : Int
        get() {
            val o = __offset(44); return if (o != 0) __vector_len(o) else 0
        }
    fun dtcs(j: Int) : dataformat.DTC? = dtcs(dataformat.DTC(), j)
    fun dtcs(obj: dataformat.DTC, j: Int) : dataformat.DTC? {
        val o = __offset(46)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val dtcsLength : Int
        get() {
            val o = __offset(46); return if (o != 0) __vector_len(o) else 0
        }
    fun audiences(j: Int) : dataformat.Audience? = audiences(dataformat.Audience(), j)
    fun audiences(obj: dataformat.Audience, j: Int) : dataformat.Audience? {
        val o = __offset(48)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val audiencesLength : Int
        get() {
            val o = __offset(48); return if (o != 0) __vector_len(o) else 0
        }
    fun additionalAudiences(j: Int) : dataformat.AdditionalAudience? = additionalAudiences(dataformat.AdditionalAudience(), j)
    fun additionalAudiences(obj: dataformat.AdditionalAudience, j: Int) : dataformat.AdditionalAudience? {
        val o = __offset(50)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val additionalAudiencesLength : Int
        get() {
            val o = __offset(50); return if (o != 0) __vector_len(o) else 0
        }
    fun states(j: Int) : dataformat.State? = states(dataformat.State(), j)
    fun states(obj: dataformat.State, j: Int) : dataformat.State? {
        val o = __offset(52)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val statesLength : Int
        get() {
            val o = __offset(52); return if (o != 0) __vector_len(o) else 0
        }
    fun preConditionStateRefs(j: Int) : dataformat.PreConditionStateRef? = preConditionStateRefs(dataformat.PreConditionStateRef(), j)
    fun preConditionStateRefs(obj: dataformat.PreConditionStateRef, j: Int) : dataformat.PreConditionStateRef? {
        val o = __offset(54)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val preConditionStateRefsLength : Int
        get() {
            val o = __offset(54); return if (o != 0) __vector_len(o) else 0
        }
    fun stateTransitions(j: Int) : dataformat.StateTransition? = stateTransitions(dataformat.StateTransition(), j)
    fun stateTransitions(obj: dataformat.StateTransition, j: Int) : dataformat.StateTransition? {
        val o = __offset(56)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stateTransitionsLength : Int
        get() {
            val o = __offset(56); return if (o != 0) __vector_len(o) else 0
        }
    fun stateTransitionRefs(j: Int) : dataformat.StateTransitionRef? = stateTransitionRefs(dataformat.StateTransitionRef(), j)
    fun stateTransitionRefs(obj: dataformat.StateTransitionRef, j: Int) : dataformat.StateTransitionRef? {
        val o = __offset(58)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stateTransitionRefsLength : Int
        get() {
            val o = __offset(58); return if (o != 0) __vector_len(o) else 0
        }
    fun stateCharts(j: Int) : dataformat.StateChart? = stateCharts(dataformat.StateChart(), j)
    fun stateCharts(obj: dataformat.StateChart, j: Int) : dataformat.StateChart? {
        val o = __offset(60)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stateChartsLength : Int
        get() {
            val o = __offset(60); return if (o != 0) __vector_len(o) else 0
        }
    fun comParams(j: Int) : dataformat.ComParam? = comParams(dataformat.ComParam(), j)
    fun comParams(obj: dataformat.ComParam, j: Int) : dataformat.ComParam? {
        val o = __offset(62)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val comParamsLength : Int
        get() {
            val o = __offset(62); return if (o != 0) __vector_len(o) else 0
        }
    fun comParamSubSets(j: Int) : dataformat.ComParamSubSet? = comParamSubSets(dataformat.ComParamSubSet(), j)
    fun comParamSubSets(obj: dataformat.ComParamSubSet, j: Int) : dataformat.ComParamSubSet? {
        val o = __offset(64)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val comParamSubSetsLength : Int
        get() {
            val o = __offset(64); return if (o != 0) __vector_len(o) else 0
        }
    fun protocols(j: Int) : dataformat.Protocol? = protocols(dataformat.Protocol(), j)
    fun protocols(obj: dataformat.Protocol, j: Int) : dataformat.Protocol? {
        val o = __offset(66)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val protocolsLength : Int
        get() {
            val o = __offset(66); return if (o != 0) __vector_len(o) else 0
        }
    fun protStacks(j: Int) : dataformat.ProtStack? = protStacks(dataformat.ProtStack(), j)
    fun protStacks(obj: dataformat.ProtStack, j: Int) : dataformat.ProtStack? {
        val o = __offset(68)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val protStacksLength : Int
        get() {
            val o = __offset(68); return if (o != 0) __vector_len(o) else 0
        }
    fun libraries(j: Int) : dataformat.Library? = libraries(dataformat.Library(), j)
    fun libraries(obj: dataformat.Library, j: Int) : dataformat.Library? {
        val o = __offset(70)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val librariesLength : Int
        get() {
            val o = __offset(70); return if (o != 0) __vector_len(o) else 0
        }
    fun ecuSharedDatas(j: Int) : dataformat.EcuSharedData? = ecuSharedDatas(dataformat.EcuSharedData(), j)
    fun ecuSharedDatas(obj: dataformat.EcuSharedData, j: Int) : dataformat.EcuSharedData? {
        val o = __offset(72)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val ecuSharedDatasLength : Int
        get() {
            val o = __offset(72); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsEcuData(_bb: ByteBuffer): EcuData = getRootAsEcuData(_bb, EcuData())
        fun getRootAsEcuData(_bb: ByteBuffer, obj: EcuData): EcuData {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEcuData(builder: FlatBufferBuilder, versionOffset: Int, ecuNameOffset: Int, revisionOffset: Int, metadataOffset: Int, featureFlagsOffset: Int, functClassesOffset: Int, unitsOffset: Int, dopsOffset: Int, tablesOffset: Int, tableRowsOffset: Int, paramsOffset: Int, requestsOffset: Int, responsesOffset: Int, diagCodedTypesOffset: Int, sdsOffset: Int, sdgsOffset: Int, sdgssOffset: Int, diagServicesOffset: Int, singleEcuJobsOffset: Int, variantsOffset: Int, functionalGroupsOffset: Int, dtcsOffset: Int, audiencesOffset: Int, additionalAudiencesOffset: Int, statesOffset: Int, preConditionStateRefsOffset: Int, stateTransitionsOffset: Int, stateTransitionRefsOffset: Int, stateChartsOffset: Int, comParamsOffset: Int, comParamSubSetsOffset: Int, protocolsOffset: Int, protStacksOffset: Int, librariesOffset: Int, ecuSharedDatasOffset: Int) : Int {
            builder.startTable(35)
            addEcuSharedDatas(builder, ecuSharedDatasOffset)
            addLibraries(builder, librariesOffset)
            addProtStacks(builder, protStacksOffset)
            addProtocols(builder, protocolsOffset)
            addComParamSubSets(builder, comParamSubSetsOffset)
            addComParams(builder, comParamsOffset)
            addStateCharts(builder, stateChartsOffset)
            addStateTransitionRefs(builder, stateTransitionRefsOffset)
            addStateTransitions(builder, stateTransitionsOffset)
            addPreConditionStateRefs(builder, preConditionStateRefsOffset)
            addStates(builder, statesOffset)
            addAdditionalAudiences(builder, additionalAudiencesOffset)
            addAudiences(builder, audiencesOffset)
            addDtcs(builder, dtcsOffset)
            addFunctionalGroups(builder, functionalGroupsOffset)
            addVariants(builder, variantsOffset)
            addSingleEcuJobs(builder, singleEcuJobsOffset)
            addDiagServices(builder, diagServicesOffset)
            addSdgss(builder, sdgssOffset)
            addSdgs(builder, sdgsOffset)
            addSds(builder, sdsOffset)
            addDiagCodedTypes(builder, diagCodedTypesOffset)
            addResponses(builder, responsesOffset)
            addRequests(builder, requestsOffset)
            addParams(builder, paramsOffset)
            addTableRows(builder, tableRowsOffset)
            addTables(builder, tablesOffset)
            addDops(builder, dopsOffset)
            addUnits(builder, unitsOffset)
            addFunctClasses(builder, functClassesOffset)
            addFeatureFlags(builder, featureFlagsOffset)
            addMetadata(builder, metadataOffset)
            addRevision(builder, revisionOffset)
            addEcuName(builder, ecuNameOffset)
            addVersion(builder, versionOffset)
            return endEcuData(builder)
        }
        fun startEcuData(builder: FlatBufferBuilder) = builder.startTable(35)
        fun addVersion(builder: FlatBufferBuilder, version: Int) = builder.addOffset(0, version, 0)
        fun addEcuName(builder: FlatBufferBuilder, ecuName: Int) = builder.addOffset(1, ecuName, 0)
        fun addRevision(builder: FlatBufferBuilder, revision: Int) = builder.addOffset(2, revision, 0)
        fun addMetadata(builder: FlatBufferBuilder, metadata: Int) = builder.addOffset(3, metadata, 0)
        fun createMetadataVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startMetadataVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addFeatureFlags(builder: FlatBufferBuilder, featureFlags: Int) = builder.addOffset(4, featureFlags, 0)
        fun createFeatureFlagsVector(builder: FlatBufferBuilder, data: ByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i])
            }
            return builder.endVector()
        }
        fun startFeatureFlagsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addFunctClasses(builder: FlatBufferBuilder, functClasses: Int) = builder.addOffset(5, functClasses, 0)
        fun createFunctClassesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startFunctClassesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addUnits(builder: FlatBufferBuilder, units: Int) = builder.addOffset(6, units, 0)
        fun createUnitsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startUnitsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDops(builder: FlatBufferBuilder, dops: Int) = builder.addOffset(7, dops, 0)
        fun createDopsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDopsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addTables(builder: FlatBufferBuilder, tables: Int) = builder.addOffset(8, tables, 0)
        fun createTablesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startTablesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addTableRows(builder: FlatBufferBuilder, tableRows: Int) = builder.addOffset(9, tableRows, 0)
        fun createTableRowsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startTableRowsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addParams(builder: FlatBufferBuilder, params: Int) = builder.addOffset(10, params, 0)
        fun createParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addRequests(builder: FlatBufferBuilder, requests: Int) = builder.addOffset(11, requests, 0)
        fun createRequestsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startRequestsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addResponses(builder: FlatBufferBuilder, responses: Int) = builder.addOffset(12, responses, 0)
        fun createResponsesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startResponsesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDiagCodedTypes(builder: FlatBufferBuilder, diagCodedTypes: Int) = builder.addOffset(13, diagCodedTypes, 0)
        fun createDiagCodedTypesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDiagCodedTypesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSds(builder: FlatBufferBuilder, sds: Int) = builder.addOffset(14, sds, 0)
        fun createSdsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startSdsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(15, sdgs, 0)
        fun createSdgsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startSdgsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSdgss(builder: FlatBufferBuilder, sdgss: Int) = builder.addOffset(16, sdgss, 0)
        fun createSdgssVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startSdgssVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDiagServices(builder: FlatBufferBuilder, diagServices: Int) = builder.addOffset(17, diagServices, 0)
        fun createDiagServicesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDiagServicesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSingleEcuJobs(builder: FlatBufferBuilder, singleEcuJobs: Int) = builder.addOffset(18, singleEcuJobs, 0)
        fun createSingleEcuJobsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startSingleEcuJobsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addVariants(builder: FlatBufferBuilder, variants: Int) = builder.addOffset(19, variants, 0)
        fun createVariantsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startVariantsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addFunctionalGroups(builder: FlatBufferBuilder, functionalGroups: Int) = builder.addOffset(20, functionalGroups, 0)
        fun createFunctionalGroupsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startFunctionalGroupsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDtcs(builder: FlatBufferBuilder, dtcs: Int) = builder.addOffset(21, dtcs, 0)
        fun createDtcsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDtcsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addAudiences(builder: FlatBufferBuilder, audiences: Int) = builder.addOffset(22, audiences, 0)
        fun createAudiencesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startAudiencesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addAdditionalAudiences(builder: FlatBufferBuilder, additionalAudiences: Int) = builder.addOffset(23, additionalAudiences, 0)
        fun createAdditionalAudiencesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startAdditionalAudiencesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addStates(builder: FlatBufferBuilder, states: Int) = builder.addOffset(24, states, 0)
        fun createStatesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStatesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addPreConditionStateRefs(builder: FlatBufferBuilder, preConditionStateRefs: Int) = builder.addOffset(25, preConditionStateRefs, 0)
        fun createPreConditionStateRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPreConditionStateRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addStateTransitions(builder: FlatBufferBuilder, stateTransitions: Int) = builder.addOffset(26, stateTransitions, 0)
        fun createStateTransitionsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStateTransitionsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addStateTransitionRefs(builder: FlatBufferBuilder, stateTransitionRefs: Int) = builder.addOffset(27, stateTransitionRefs, 0)
        fun createStateTransitionRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStateTransitionRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addStateCharts(builder: FlatBufferBuilder, stateCharts: Int) = builder.addOffset(28, stateCharts, 0)
        fun createStateChartsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStateChartsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addComParams(builder: FlatBufferBuilder, comParams: Int) = builder.addOffset(29, comParams, 0)
        fun createComParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addComParamSubSets(builder: FlatBufferBuilder, comParamSubSets: Int) = builder.addOffset(30, comParamSubSets, 0)
        fun createComParamSubSetsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComParamSubSetsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addProtocols(builder: FlatBufferBuilder, protocols: Int) = builder.addOffset(31, protocols, 0)
        fun createProtocolsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startProtocolsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addProtStacks(builder: FlatBufferBuilder, protStacks: Int) = builder.addOffset(32, protStacks, 0)
        fun createProtStacksVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startProtStacksVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addLibraries(builder: FlatBufferBuilder, libraries: Int) = builder.addOffset(33, libraries, 0)
        fun createLibrariesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startLibrariesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addEcuSharedDatas(builder: FlatBufferBuilder, ecuSharedDatas: Int) = builder.addOffset(34, ecuSharedDatas, 0)
        fun createEcuSharedDatasVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startEcuSharedDatasVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endEcuData(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishEcuDataBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedEcuDataBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
