// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class OdxData : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : OdxData {
        __init(_i, _bb)
        return this
    }
    val version : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val versionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun versionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    fun ecuNames(j: Int) : String? {
        val o = __offset(6)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val ecuNamesLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    fun metadata(j: Int) : dataformat.KeyValue? = metadata(dataformat.KeyValue(), j)
    fun metadata(obj: dataformat.KeyValue, j: Int) : dataformat.KeyValue? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val metadataLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    fun featureFlags(j: Int) : Byte {
        val o = __offset(10)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1)
        } else {
            0
        }
    }
    val featureFlagsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val featureFlagsAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun featureFlagsInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    fun ecus(j: Int) : dataformat.EcuData? = ecus(dataformat.EcuData(), j)
    fun ecus(obj: dataformat.EcuData, j: Int) : dataformat.EcuData? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val ecusLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    val shared : dataformat.SharedData? get() = shared(dataformat.SharedData())
    fun shared(obj: dataformat.SharedData) : dataformat.SharedData? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsOdxData(_bb: ByteBuffer): OdxData = getRootAsOdxData(_bb, OdxData())
        fun getRootAsOdxData(_bb: ByteBuffer, obj: OdxData): OdxData {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createOdxData(builder: FlatBufferBuilder, versionOffset: Int, ecuNamesOffset: Int, metadataOffset: Int, featureFlagsOffset: Int, ecusOffset: Int, sharedOffset: Int) : Int {
            builder.startTable(6)
            addShared(builder, sharedOffset)
            addEcus(builder, ecusOffset)
            addFeatureFlags(builder, featureFlagsOffset)
            addMetadata(builder, metadataOffset)
            addEcuNames(builder, ecuNamesOffset)
            addVersion(builder, versionOffset)
            return endOdxData(builder)
        }
        fun startOdxData(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addVersion(builder: FlatBufferBuilder, version: Int) = builder.addOffset(0, version, 0)
        fun addEcuNames(builder: FlatBufferBuilder, ecuNames: Int) = builder.addOffset(1, ecuNames, 0)
        fun createEcuNamesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startEcuNamesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addMetadata(builder: FlatBufferBuilder, metadata: Int) = builder.addOffset(2, metadata, 0)
        fun createMetadataVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startMetadataVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addFeatureFlags(builder: FlatBufferBuilder, featureFlags: Int) = builder.addOffset(3, featureFlags, 0)
        fun createFeatureFlagsVector(builder: FlatBufferBuilder, data: ByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i])
            }
            return builder.endVector()
        }
        fun startFeatureFlagsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addEcus(builder: FlatBufferBuilder, ecus: Int) = builder.addOffset(4, ecus, 0)
        fun createEcusVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startEcusVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addShared(builder: FlatBufferBuilder, shared: Int) = builder.addOffset(5, shared, 0)
        fun endOdxData(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishOdxDataBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedOdxDataBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
