// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SharedData : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SharedData {
        __init(_i, _bb)
        return this
    }
    fun functionalGroups(j: Int) : dataformat.FunctionalGroup? = functionalGroups(dataformat.FunctionalGroup(), j)
    fun functionalGroups(obj: dataformat.FunctionalGroup, j: Int) : dataformat.FunctionalGroup? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val functionalGroupsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    fun ecuSharedData(j: Int) : dataformat.EcuSharedData? = ecuSharedData(dataformat.EcuSharedData(), j)
    fun ecuSharedData(obj: dataformat.EcuSharedData, j: Int) : dataformat.EcuSharedData? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val ecuSharedDataLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsSharedData(_bb: ByteBuffer): SharedData = getRootAsSharedData(_bb, SharedData())
        fun getRootAsSharedData(_bb: ByteBuffer, obj: SharedData): SharedData {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSharedData(builder: FlatBufferBuilder, functionalGroupsOffset: Int, ecuSharedDataOffset: Int) : Int {
            builder.startTable(2)
            addEcuSharedData(builder, ecuSharedDataOffset)
            addFunctionalGroups(builder, functionalGroupsOffset)
            return endSharedData(builder)
        }
        fun startSharedData(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addFunctionalGroups(builder: FlatBufferBuilder, functionalGroups: Int) = builder.addOffset(0, functionalGroups, 0)
        fun createFunctionalGroupsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startFunctionalGroupsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addEcuSharedData(builder: FlatBufferBuilder, ecuSharedData: Int) = builder.addOffset(1, ecuSharedData, 0)
        fun createEcuSharedDataVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startEcuSharedDataVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endSharedData(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
