// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Structure : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Structure {
        __init(_i, _bb)
        return this
    }
    val byteSize : UInt?
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val isVisible : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else true
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsStructure(_bb: ByteBuffer): Structure = getRootAsStructure(_bb, Structure())
        fun getRootAsStructure(_bb: ByteBuffer, obj: Structure): Structure {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStructure(builder: FlatBufferBuilder, byteSize: UInt?, isVisible: Boolean) : Int {
            builder.startTable(2)
            byteSize?.run { addByteSize(builder, byteSize) }
            addIsVisible(builder, isVisible)
            return endStructure(builder)
        }
        fun startStructure(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addByteSize(builder: FlatBufferBuilder, byteSize: UInt) = builder.addInt(0, byteSize.toInt(), 0)
        fun addIsVisible(builder: FlatBufferBuilder, isVisible: Boolean) = builder.addBoolean(1, isVisible, true)
        fun endStructure(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
